[tox]
envlist = lint, ha-stable, ha-major, ha-beta

[testenv]
description = Run pytest
basepython = python3.14
skip_install = true
passenv = HA_VERSION
deps =
    homeassistant=={env:HA_VERSION}
    pytest-homeassistant-custom-component>=0.13.320
    coverage
commands =
    coverage run -m pytest {posargs}
    coverage report

[testenv:ha-stable]
description = Test with latest HA stable (any patch version)
setenv =
    HA_VERSION = {env:HA_STABLE_VERSION}

[testenv:ha-major]
description = Test with latest HA major release (x.y.0)
setenv =
    HA_VERSION = {env:HA_MAJOR_VERSION}

[testenv:ha-previous-stable]
description = Test with previous HA stable
setenv =
    HA_VERSION = {env:HA_PREVIOUS_STABLE_VERSION}

[testenv:ha-beta]
description = Test with latest HA beta
setenv =
    HA_VERSION = {env:HA_BETA_VERSION}

[testenv:lint]
description = Run linters with pre-commit
setenv =
    HA_VERSION = {env:HA_STABLE_VERSION}
deps =
    homeassistant=={env:HA_VERSION}
    pytest-homeassistant-custom-component>=0.13.320
    colorlog
    flake8
    flake8-docstrings
    mypy
    pylint
    pylint-strict-informational
    pre-commit
    ruff
    black
    packaging
    PyGithub
    pyupgrade
    yamllint
commands = pre-commit run --all-files
